cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', views.cart_add, name='cart_add'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('export/', views.cart_export, name='cart_export'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
    path('retrieve/', views.cart_retrieve, name='cart_retrieve'),
    path('total/', views.cart_total, name='cart_total'),
    path('update/<int:book_id>/', views.cart_update, name='cart_update'),
    ]

pdf/urls.py
from django.urls import path

from . import views

app_name = 'pdf'

urlpatterns = [
    path('export/', views.books_to_pdf, name='books_to_pdf'),
    ]

orders/models.py
from django.db import models

from books.models import Book


class Order(models.Model):
    id = models.CharField(primary_key=True, max_length=6)
    inst_name = models.CharField(max_length=250)
    amount_requested = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id} for {self.inst_name}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name='order_items', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

cart/forms.py
from django import forms


class CartAddBookForm(forms.Form):
    quantity = forms.IntegerField(
        min_value=1,
        max_value=99,
        widget=forms.NumberInput(attrs={'class': 'form-control-sm'})
        )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
        )

cart/views.py
import csv
from urllib.parse import urlparse

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from django.http import HttpResponseBadRequest

from books.models import Book
from orders.forms import OrderCreateForm
from orders.models import Order
from .cart import Cart
from .forms import CartAddBookForm


def is_same_host(url, request):
    # Extract the host from the URL
    parsed_url = urlparse(url)
    redirect_host = parsed_url.netloc

    # Extract the host from the current request
    current_host = request.get_host()

    # Compare the hosts
    return redirect_host == current_host


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddBookForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book, quantity=cd['quantity'], override_quantity=cd['override'])
        message = "<em>" + book.title[:27] + '...</em> added.'
        messages.add_message(request, messages.SUCCESS, message=message)

    if request.headers.get('HX-Request', False):
        response = render(request, "toast.html")
        response['HX-Trigger'] = 'updateTotal'
        return response

    # Hack to keep book query filter query params intact after POST
    previous_url = request.META.get('HTTP_REFERER', 'books:book_list')

    # Check if the previous URL is from the same host
    if not is_same_host(previous_url, request):
        return HttpResponseBadRequest("Invalid redirect URL")

    return redirect(previous_url)


@require_POST
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    message = 'Your selection list has been cleared.'
    messages.add_message(request, messages.SUCCESS, message=message)

    return redirect('books:book_list')


def cart_detail(request):
    cart = Cart(request)
    order = OrderCreateForm

    for item in cart:
        item['update_quantity_form'] = CartAddBookForm(initial={'quantity': item['quantity'], 'override': True})

    return render(request, 'cart/detail.html', {'cart': cart, 'order': order})


def cart_export(request):
    cart = Cart(request)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=COBAA-Selections.csv'
    writer = csv.writer(response)
    # write header
    writer.writerow(['title', 'authors', 'awards', 'quantity'])
    # write rows
    for item in cart:
        book = item['book']
        authors = ';'.join([author.name for author in book.authors.all()])
        awards = ';'.join([str(award) for award in book.awards.all()])
        writer.writerow([book.title, authors, awards, item['quantity']])
    return response


@require_POST
def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)

    if request.headers.get('HX-Request', False):
        response = HttpResponse('')
        response['HX-Trigger'] = 'updateTotal'
        return response

    return redirect('cart:cart_detail')


@require_POST
def cart_retrieve(request):
    # clear the cart
    request.session.flush()
    cart = Cart(request)

    try:
        order_id = request.POST.get('order_id', None)
        previous_order = Order.objects.get(id=order_id)
        cart.retrieve(previous_order)
        message = str(previous_order.items.count()) + ' titles retrieved.'
        messages.add_message(request, messages.SUCCESS, message=message)
        return redirect('cart:cart_detail')
    except Order.DoesNotExist:
        message = 'Code not recognized. Please try again.'
        messages.add_message(request, messages.ERROR, message=message)
        return redirect('books:book_list')


def cart_total(request):
    # return current total items
    cart = Cart(request)
    return render(request, "total.html")


@require_POST
def cart_update(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddBookForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])

        message = "<em>" + book.title[:27] + '...</em> updated.'
        messages.add_message(request, messages.SUCCESS, message=message)

        if request.headers.get('HX-Request', False):
            response = render(request, "toast.html")
            response['HX-Trigger'] = 'updateTotal'
            return response

    return redirect('cart:cart_detail')

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}  {% load django_bootstrap5 %}

{% block title %}My Selected Titles{% endblock %}

{% block content %}

  {% include 'toolbar.html' %}

  <table class="table table-hover align-middle" style="font-size:0.88rem;">
    <colgroup>
      <col width="40%">
      <col width="40%">
      <col width="20%">
    </colgroup>
    <thead>
    <tr>
      <th>Title</th>
      <th>Author / Illustrators</th>
      <th>Quantity</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
      {% with book=item.book %}
        <tr>
          <td>{{ book.title }}</td>
          <td>{{ book.authors.all|join:" &amp; " }}</td>
          <td>
            <form class="row row-cols-lg-auto g-3 align-items-center" hx-post="{% url "cart:cart_update" book.id %}" hx-target="#toast">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.override }}
              <input type="submit" value="Update" class="btn btn-sm btn-outline-secondary mx-2">
            <button class="btn btn-sm btn-danger"
                    hx-post="{% url "cart:cart_remove" book.id %}"
                    hx-confirm="Remove this title?"
                    hx-target="closest tr"
                    hx-swap="outerHTML swap:0.4s">
              <i class="lni lni-trash-can"></i>&nbsp;Remove
            </button>
              {% csrf_token %}
            </form>
          </td>
        </tr>
      {% endwith %}
    {% endfor %}
    </tbody>
  </table>

  {% include 'toolbar.html' %}

  <div id="myModal" class="modal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Almost there!</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Please enter the following information for the PDF</p>
          <form id="orderForm" class="form-group" action="{% url "pdf:books_to_pdf" %}" target="_blank" method="post">
            <div class="mb-3">
              <label for="id_inst_name" class="form-label">Institution Name</label>
              {{ order.inst_name }}
            </div>
            <label>Total Amount</label>
            <div class="input-group">
              <div class="input-group-text">$</div>
              {{ order.amount_requested }}
            </div>
            <div id="orderHelp" class="form-text">Should reflect the total costs of your selections.</div>
            {% csrf_token %}
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" form="orderForm" class="btn btn-primary">Generate PDF</button>
        </div>
      </div>
    </div>
  </div>

  <script>
      let myModal = new bootstrap.Modal(document.getElementById('myModal'), {
          keyboard: false
      })
      let myInput = document.getElementById('id_inst_name')
      myModal._element.addEventListener(
          'shown.bs.modal', function () {
              myInput.focus()
          })
      let myForm = document.getElementById('orderForm')
      myForm.addEventListener('submit', function () {
          myModal.hide()
      })
  </script>

{% endblock content %}