books/urls.py
from django.urls import path

from .views import AwardListView, BookListView

app_name = 'books'

urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('books/', BookListView.as_view(), name='book_list'),
    path('awards/', AwardListView.as_view(), name='award_list'),
    ]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', views.cart_add, name='cart_add'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('export/', views.cart_export, name='cart_export'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
    path('retrieve/', views.cart_retrieve, name='cart_retrieve'),
    path('total/', views.cart_total, name='cart_total'),
    path('update/<int:book_id>/', views.cart_update, name='cart_update'),
    ]

pdf/urls.py
from django.urls import path

from . import views

app_name = 'pdf'

urlpatterns = [
    path('export/', views.books_to_pdf, name='books_to_pdf'),
    ]

books/models.py
from datetime import date

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.template.defaultfilters import truncatewords
from django.urls import reverse


class Tag(models.Model):
    tag = models.CharField('Tags', max_length=55, unique=True)

    class Meta:
        ordering = ['tag']

    def __str__(self):
        return self.tag


class Author(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class BookManager(models.Manager):
    def get_queryset(self):
        return super(BookManager, self).get_queryset().filter(hidden=0)


class Book(models.Model):
    title = models.CharField('Book Title', max_length=250)
    authors = models.ManyToManyField(Author, related_name='books')
    tags = models.ManyToManyField(Tag, verbose_name='tags', blank=True)
    hidden = models.BooleanField(default=False, verbose_name='Hidden from search results')

    def get_absolute_url(self):
        return reverse('books:book_list', args=[self.id])

    objects = models.Manager()
    published = BookManager()

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class AwardQuerySet(models.query.QuerySet):
    def published(self):
        return self.filter(hidden=False)


class AwardManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return AwardQuerySet(self.model)

    def published(self, *args, **kwargs):
        return self.get_queryset().published(*args, **kwargs)


class Award(models.Model):
    award = models.CharField(max_length=75,
                             choices=[
                                 ('a', 'Anisfield-Wolf'),
                                 ('p', 'Arnold Adoff'),
                                 ('b', 'Buckeye Children\'s & Teen'),
                                 ('c', 'Choose to Read Ohio'),
                                 ('d', 'Dayton Literary Peace Prize'),
                                 ('f', 'Floyd\'s Pick'),
                                 ('j', 'James Cook'),
                                 ('m', 'Nancy Dasher Book Awards'),
                                 ('n', 'Norman A. Sugarman'),
                                 ('o', 'Ohio Book Award'),
                                 ('s', 'Scott O\'Dell'),
                                 ('t', 'Thurber Prize')
                                 ])
    year = models.SmallIntegerField(validators=[MinValueValidator(1900, message="Invalid date"),
                                                MaxValueValidator(date.today().year + 1, message="Invalid date")])
    prize = models.CharField(max_length=1,
                             choices=(
                                 ('c', 'Featured Title'),
                                 ('f', 'Finalist'),
                                 ('h', 'Honor'),
                                 ('m', 'Honorable Mention'),
                                 ('n', 'Nominee'),
                                 ('r', 'Runner-Up'),
                                 ('s', 'Special Honor'),
                                 ('w', 'Winner'),
                                 ),
                             verbose_name="Prize")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='awards')
    hidden = models.BooleanField(default=False, verbose_name='Hidden from search results')

    @property
    def get_short_book_title(self):
        return truncatewords(self.book.title, 10)

    @property
    def get_authors(self):
        return ' & '.join([author.name for author in self.book.authors.all()])

    objects = AwardManager()

    class Meta:
        ordering = ['award', '-year']

    def __str__(self):
        return f'{self.year} {self.get_award_display()} - {self.get_prize_display()}'

books/views.py
from django.views.generic.list import ListView

from cart.forms import CartAddBookForm
from .filters import BookFilter
from .models import Award, Book


class AwardListView(ListView):
    model = Award
    template_name = 'awards/award_list.html'

    paginate_by = 20

    def get_queryset(self):
        queryset = Award.objects.all().filter(hidden=0).order_by('award', '-year', 'book__title')

        return queryset


class BookListView(ListView):
    model = Book
    template_name = 'books/book_list.html'

    paginate_by = 20

    def get_queryset(self):
        queryset = Book.published.all().order_by('title').distinct()
        filtered_list = BookFilter(self.request.GET, queryset=queryset)

        return filtered_list.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context['cart_form'] = CartAddBookForm()

        return context

books/templates/books/book_list.html
{% extends 'base.html' %}
{% load static %}  {% load django_bootstrap5 %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <form role="form" class="form" method="get">
                <div class="row">
                    <div class="col-md-6">
                        {% bootstrap_field books.form.awards__award bound_css_class="" %}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field books.form.award_year bound_css_class="" %}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        {% bootstrap_field books.form.keywords value="" placeholder="Ex: Berenstain" bound_css_class=""%}
                        <div class="form-check form-switch">
                            {% if request.GET.winner == 'true' %}
                                <input class="form-check-input" type="checkbox" name="winner" id="id_winner"
                                       value="true" checked>
                            {% else %}
                                <input class="form-check-input" type="checkbox" name="winner" id="id_winner"
                                       value="true">
                            {% endif %}
                            <label class="form-check-label" for="winner">Winners only</label>
                        </div>
                    </div>
                </div>

                <div class="row mt-1">
                    <div class="mb-3">
                        {% bootstrap_button content='Search' button_type="submit" size="md"%}
                </div>
                </div>
            </form>
        </div>
    </div>

    {% include 'paginator.html' %}

    <table class="table table-hover align-middle" style="font-size:0.88rem;">
        <thead>
        <tr>
            <th>Title</th>
            <th>Authors / Illustrators</th>
            <th>Awards</th>
            <th class="text-end">Quantity</th>
        </tr>
        </thead>
        {% for book in book_list %}
            <tr>
                <td>
                    <strong>{{ book.title|truncatechars:60 }}</strong><br>
                    <span class="small">
              {{ book.tags.all|join:'<span style="color:#424242"> &bull; </span>' }}
            </span>
                </td>
                <td>{{ book.authors.all|join:'<br />' }}</td>
                <td>{{ book.awards.published|join:'<br>' }}</td>
                <td>
                    <div class="input-group input-group-sm justify-content-end">
                        <form class="cart_form" hx-post="{% url "cart:cart_add" book.id %}" hx-target="#toast">
                            {% for field in cart_form %}
                                {{ field }}
                            {% endfor %}
                            {% csrf_token %}
                            <input type="submit" class="btn btn-sm btn-info" value="Add +">
                        </form>
                    </div>
                </td>
            </tr>
        {% empty %}
            <p>No results found.</p>
        {% endfor %}
    </table>

    {% include 'paginator.html' %}

{% endblock content %}